# Generated by Django 5.2.8 on 2025-11-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_company_alter_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='address_building',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом/корпус'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_office',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Офис'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_zip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='client',
            name='audit_report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата аудиторского отчёта'),
        ),
        migrations.AddField(
            model_name='client',
            name='audit_report_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='№ аудиторского отчёта'),
        ),
        migrations.AddField(
            model_name='client',
            name='audit_report_paragraph',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Параграф аудиторского отчёта'),
        ),
        migrations.AddField(
            model_name='client',
            name='audit_report_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид аудиторского отчёта'),
        ),
        migrations.AddField(
            model_name='client',
            name='authorized_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email уполномоченного лица'),
        ),
        migrations.AddField(
            model_name='client',
            name='authorized_person_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО уполномоченного лица'),
        ),
        migrations.AddField(
            model_name='client',
            name='contract_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Конечный срок выполнения договора'),
        ),
        migrations.AddField(
            model_name='client',
            name='cw_controls_done',
            field=models.BooleanField(default=False, verbose_name='Выполнены ли контрольные процедуры в CW'),
        ),
        migrations.AddField(
            model_name='client',
            name='edrpou',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ЕГРПОУ'),
        ),
        migrations.AddField(
            model_name='client',
            name='engagement_subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Предмет задания'),
        ),
        migrations.AddField(
            model_name='client',
            name='kved',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КВЭД'),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AddField(
            model_name='client',
            name='mandatory_audit',
            field=models.BooleanField(default=False, verbose_name='Обязательный аудит (обзор)'),
        ),
        migrations.AddField(
            model_name='client',
            name='poi',
            field=models.BooleanField(default=False, verbose_name='ПОИ'),
        ),
        migrations.AddField(
            model_name='client',
            name='reporting_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчётный период'),
        ),
        migrations.AddField(
            model_name='client',
            name='requisites_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='client',
            name='requisites_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора/документа'),
        ),
        migrations.AddField(
            model_name='client',
            name='requisites_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='№ договора/документа'),
        ),
        migrations.AddField(
            model_name='client',
            name='requisites_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='НДС'),
        ),
        migrations.AddField(
            model_name='client',
            name='supervision_body',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Орган надзора'),
        ),
        migrations.AddField(
            model_name='client',
            name='supervision_notice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправленного уведомления в орган надзора'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
    ]
