# Generated by Django 5.2.8 on 2025-11-25 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_client_company_remove_client_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assistant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_assistant2', to=settings.AUTH_USER_MODEL, verbose_name='Ассистент 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='assistant3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_assistant3', to=settings.AUTH_USER_MODEL, verbose_name='Ассистент 3'),
        ),
        migrations.AddField(
            model_name='client',
            name='assistant4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_assistant4', to=settings.AUTH_USER_MODEL, verbose_name='Ассистент 4'),
        ),
        migrations.AddField(
            model_name='client',
            name='auditor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_auditor2', to=settings.AUTH_USER_MODEL, verbose_name='Аудитор 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='auditor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_auditor3', to=settings.AUTH_USER_MODEL, verbose_name='Аудитор 3'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_assistant1', to=settings.AUTH_USER_MODEL, verbose_name='Ассистент 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_auditor1', to=settings.AUTH_USER_MODEL, verbose_name='Аудитор 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='qa_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_qa_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер КК'),
        ),
    ]
