# Generated by Django 5.2.8 on 2025-11-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_audit_report_paragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='planned_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Рабочие часы (план)'),
        ),
    ]
