# Generated by Django 5.2.8 on 2025-11-27 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_planned_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_building',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Будинок/корпус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_office',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Офіс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_zip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Індекс'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_assistant1', to=settings.AUTH_USER_MODEL, verbose_name='Асистент 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assistant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_assistant2', to=settings.AUTH_USER_MODEL, verbose_name='Асистент 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assistant3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_assistant3', to=settings.AUTH_USER_MODEL, verbose_name='Асистент 3'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assistant4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_assistant4', to=settings.AUTH_USER_MODEL, verbose_name='Асистент 4'),
        ),
        migrations.AlterField(
            model_name='client',
            name='audit_report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата аудиторського звіту'),
        ),
        migrations.AlterField(
            model_name='client',
            name='audit_report_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='№ аудиторського звіту'),
        ),
        migrations.AlterField(
            model_name='client',
            name='audit_report_paragraph',
            field=models.CharField(blank=True, choices=[('OTHER', 'Параграф: Інше'), ('GOING_CONCERN', 'Суттєва невизначеність щодо безперервності діяльності')], max_length=255, null=True, verbose_name='Параграф аудиторського звіту'),
        ),
        migrations.AlterField(
            model_name='client',
            name='audit_report_type',
            field=models.CharField(blank=True, choices=[('QUALIFIED', 'Думка із застереженням'), ('ADVERSE', 'Негативна думка'), ('DISCLAIMER', 'Відмова від висловлення думки')], max_length=255, null=True, verbose_name='Вид аудиторського звіту'),
        ),
        migrations.AlterField(
            model_name='client',
            name='authorized_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email уповноваженої особи'),
        ),
        migrations.AlterField(
            model_name='client',
            name='authorized_person_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ПІБ уповноваженої особи'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contract_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Кінцевий строк виконання договору'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cw_controls_done',
            field=models.BooleanField(default=False, verbose_name='Контрольні процедури в CW виконані'),
        ),
        migrations.AlterField(
            model_name='client',
            name='edrpou',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='engagement_subject',
            field=models.CharField(blank=True, choices=[('O_AUDIT', 'Аудит фінансової звітності та/або консолідованої фінансової звітності (О)'), ('O_REVIEW', 'Огляд історичної фінансової звітності та проміжної фінансової інформації (О)'), ('O_ASSURANCE', 'Завдання з надання впевненості, не є аудитом або оглядом (О)'), ('I_AUDIT', 'Аудит фінансової звітності та/або консолідованої фінансової звітності (І)'), ('I_REVIEW', 'Огляд історичної фінансової звітності та проміжної фінансової інформації (І)'), ('I_ASSURANCE', 'Завдання з надання впевненості, не є аудитом або оглядом (І)'), ('RELATED', 'Супутні послуги'), ('NON_AUDIT', 'Інші неаудиторські послуги')], max_length=100, null=True, verbose_name='Предмет завдання'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kved',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КВЕД'),
        ),
        migrations.AlterField(
            model_name='client',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('FOP', 'Фізична особа-підприємець'), ('LLC', 'Товариство з обмеженою відповідальністю (ТОВ)'), ('OAO', 'Відкрите акціонерне товариство (ВАТ)'), ('ZAO', 'Закрите акціонерне товариство (ЗАТ)'), ('CHAO', 'Приватне акціонерне товариство (ПрАТ)'), ('KT', 'Командитне товариство'), ('KOLL', 'Командитне товариство з обмеженою відповідальністю'), ('PARTNER', 'Партнерства (господарські товариства)'), ('COOP', 'Кооперативи'), ('FOREIGN_BRANCH', 'Філія або представництво іноземної компанії'), ('FOREIGN_INVEST', 'Підприємства з іноземними інвестиціями'), ('INT_ORG', 'Міжнародні господарські організації'), ('FARM', 'Фермерські господарства'), ('STATE_ENT', 'Державні підприємства'), ('KAZENNOE', 'Казенні підприємства'), ('COMMUNAL', 'Комунальні підприємства'), ('LLC2', 'Товариство з обмеженою відповідальністю (інше)'), ('ODD', 'Товариство з додатковою відповідальністю'), ('GOV', 'Органи державної влади'), ('GOV_ORG', 'Державні організації (установи, заклади)'), ('POLITICAL', 'Політичні партії'), ('NGO', 'Громадські та благодійні організації'), ('PAO', 'Публічні акціонерні товариства'), ('APU', 'Аудиторська палата України')], max_length=255, null=True, verbose_name='Організаційно-правова форма'),
        ),
        migrations.AlterField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mandatory_audit',
            field=models.BooleanField(default=False, verbose_name="Обов'язковий аудит (огляд)"),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Повна назва клієнта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='planned_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Робочі години (план)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='poi',
            field=models.BooleanField(default=False, verbose_name='ПОІ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='qa_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_as_qa_manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер КК'),
        ),
        migrations.AlterField(
            model_name='client',
            name='reporting_period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Звітний період'),
        ),
        migrations.AlterField(
            model_name='client',
            name='requisites_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сума договору'),
        ),
        migrations.AlterField(
            model_name='client',
            name='requisites_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договору/документа'),
        ),
        migrations.AlterField(
            model_name='client',
            name='requisites_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='№ договору/документа'),
        ),
        migrations.AlterField(
            model_name='client',
            name='requisites_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ПДВ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='supervision_body',
            field=models.CharField(blank=True, choices=[('AGRARIAN', 'Міністерство аграрної політики та продовольства України'), ('MIA', 'Міністерство внутрішніх справ України'), ('ECOLOGY', 'Міністерство екології та природних ресурсів України'), ('ECONOMY', 'Міністерство економічного розвитку і торгівлі України'), ('ENERGY', 'Міністерство енергетики та вугільної промисловості України'), ('INFRA', 'Міністерство інфраструктури України'), ('CULTURE', 'Міністерство культури України'), ('EDU', 'Міністерство освіти і науки України'), ('HEALTH', 'Міністерство охорони здоров’я України'), ('SOCIAL', 'Міністерство соціальної політики України'), ('FINANCE', 'Міністерство фінансів України'), ('DSSZZI', 'Адміністрація Держспецзв’язку України'), ('NUCLEAR', 'Державна інспекція ядерного регулювання України'), ('REG_SERVICE', 'Державна регуляторна служба України'), ('FOOD_SAFETY', 'Держпродспоживслужба України'), ('FORESTRY', 'Держлісагентство України'), ('FISHERIES', 'Держрибагентство України'), ('EMERGENCY', 'ДСНС України'), ('ECO_INSPECTION', 'Державна екологічна інспекція України'), ('GEOLOGY', 'Державна служба геології та надр України'), ('AVIA', 'Державіаслужба України'), ('TRANSPORT', 'Укртрансбезпека'), ('CINEMA', 'Держкіно України'), ('EDU_QUALITY', 'Державна служба якості освіти України'), ('DRUG_CONTROL', 'Держлікслужба України'), ('DABI', 'ДАБІ України'), ('GEO_CADASTRE', 'Держгеокадастр України'), ('LABOR', 'Державна служба з питань праці'), ('PENSION', 'Пенсійний фонд України'), ('TAX', 'Державна фіскальна служба'), ('NCR_FIN', 'Нацкомфінпослуг'), ('NCR_EC', 'НКРЕКП'), ('NCSM', 'НКЦПФР'), ('SBU', 'Служба безпеки України'), ('ENERGY_SUPERV', 'Інспекція енергетичного нагляду України'), ('MINREGION', 'Міністерство розвитку громад та територій України'), ('SEA_RIVER_TRANSPORT', 'Морська адміністрація України'), ('NBU', 'Національний банк України')], max_length=255, null=True, verbose_name='Орган нагляду'),
        ),
        migrations.AlterField(
            model_name='client',
            name='supervision_notice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата повідомлення органу нагляду'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
    ]
