# Generated by Django 5.2.8 on 2025-11-28 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_client_address_building_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='client_docs/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Назва документа')),
                ('doc_type', models.CharField(blank=True, choices=[('charter', 'Статутний документ'), ('request', 'Запит / лист'), ('contract', 'Договір'), ('report', 'Звіт'), ('other', 'Інше')], max_length=50, null=True, verbose_name='Тип документа')),
                ('custom_label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мітка / примітка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.client', verbose_name='Клієнт')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Документ клієнта',
                'verbose_name_plural': 'Документи клієнтів',
                'ordering': ['-created_at'],
            },
        ),
    ]
