# Generated by Django 5.2.8 on 2025-11-28 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clientdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdocument',
            options={},
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('charter', 'Установчий документ'), ('request', 'Запит / лист'), ('agreement', 'Договір'), ('other', 'Інше')], max_length=50, null=True, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригінальна назва'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач, який завантажив'),
        ),
    ]
