# Generated by Django 5.2.8 on 2025-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_clientdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assistant2_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ассистент 2 (username)'),
        ),
        migrations.AddField(
            model_name='client',
            name='assistant3_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ассистент 3 (username)'),
        ),
        migrations.AddField(
            model_name='client',
            name='assistant4_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ассистент 4 (username)'),
        ),
        migrations.AddField(
            model_name='client',
            name='assistant_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ассистент 1 (username)'),
        ),
        migrations.AddField(
            model_name='client',
            name='auditor2_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Аудитор 2 (username)'),
        ),
        migrations.AddField(
            model_name='client',
            name='auditor3_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Аудитор 3 (username)'),
        ),
        migrations.AddField(
            model_name='client',
            name='auditor_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Аудитор 1 (username)'),
        ),
        migrations.AddField(
            model_name='client',
            name='manager_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Менеджер (username)'),
        ),
        migrations.AddField(
            model_name='client',
            name='qa_manager_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='QA-менеджер (username)'),
        ),
    ]
