# Generated by Django 5.2.8 on 2025-12-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_news_options_news_image_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Кінцевий строк виконання договору'),
        ),
        migrations.AddField(
            model_name='client',
            name='task_subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предмет завдання'),
        ),
    ]
