# Generated by Django 5.2.8 on 2025-12-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_client_organization_clientdocument_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='assistant2_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Асистент 2 (username)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assistant3_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Асистент 3 (username)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assistant4_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Асистент 4 (username)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='assistant_username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Асистент 1 (username)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Кінцевий строк виконання договору (додатково)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='task_subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Предмет завдання (додатково)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, verbose_name='Посилання (опціонально)'),
        ),
    ]
