# Generated by Django 5.2.8 on 2025-12-12 21:57

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_client_assistant2_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('FOP', 'Фізична особа-підприємець'), ('LLC', 'Товариство з обмеженою відповідальністю (ТОВ)'), ('OAO', 'Відкрите акціонерне товариство (ВАТ)'), ('ZAO', 'Закрите акціонерне товариство (ЗАТ)'), ('CHAO', 'Приватне акціонерне товариство (ПрАТ)'), ('KT', 'Командитне товариство'), ('KOLL', 'Командитне товариство з обмеженою відповідальністю'), ('PARTNER', 'Партнерства (господарські товариства)'), ('COOP', 'Кооперативи'), ('FOREIGN_BRANCH', 'Філія або представництво іноземної компанії'), ('FOREIGN_INVEST', 'Підприємства з іноземними інвестиціями'), ('INT_ORG', 'Міжнародні господарські організації'), ('FARM', 'Фермерські господарства'), ('STATE_ENT', 'Державні підприємства'), ('KAZENNOE', 'Казенні підприємства'), ('COMMUNAL', 'Комунальні підприємства'), ('LLC2', 'Товариство з обмеженою відповідальністю (інше)'), ('ODD', 'Товариство з додатковою відповідальністю'), ('GOV', 'Органи державної влади'), ('GOV_ORG', 'Державні організації (установи, заклади)'), ('POLITICAL', 'Політичні партії'), ('NGO', 'Громадські та благодійні організації'), ('PAO', 'Публічні акціонерні товариства'), ('APU', 'Аудиторська палата України'), ('PRIVATE_ENT', 'Приватне підприємство'), ('SUBSIDIARY_ENT', 'Дочірнє підприємство'), ('JSC', 'Акціонерне товариство')], max_length=255, null=True, verbose_name='Організаційно-правова форма'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cw_controls_done', models.BooleanField(default=False, verbose_name='Контрольні процедури в CW виконані')),
                ('audit_report_scan', models.FileField(blank=True, null=True, upload_to=core.models.client_audit_report_upload_to, verbose_name='Скан-копія аудиторського звіту')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Проект завершено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Хто завершив')),
            ],
        ),
    ]
