# Generated by Django 5.2.8 on 2025-12-12 22:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_client_legal_form_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='audit_report_scan',
            field=models.FileField(blank=True, null=True, upload_to=core.models.client_audit_report_upload_to, verbose_name='Скан-копія аудиторського звіту'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
