# Generated by Django 5.2.8 on 2025-12-12 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_client_audit_report_scan_delete_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AddField(
            model_name='client',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_clients', to=settings.AUTH_USER_MODEL, verbose_name='Хто завершив'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Проект завершено'),
        ),
    ]
