# Generated by Django 5.2.8 on 2025-12-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0021_procedurefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва кроку')),
                ('purpose', models.TextField(blank=True, verbose_name='Мета')),
                ('documentation', models.TextField(blank=True, verbose_name='Документування')),
                ('procedure_description', models.TextField(blank=True, verbose_name='Опис процедур')),
                ('expected_result', models.TextField(blank=True, verbose_name='Очікуваний результат')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Крок аудиту (шаблон)',
                'verbose_name_plural': 'Кроки аудиту (шаблони)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditSubStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва підкроку')),
                ('purpose', models.TextField(blank=True, verbose_name='Мета')),
                ('documentation', models.TextField(blank=True, verbose_name='Документування')),
                ('procedure_description', models.TextField(blank=True, verbose_name='Опис процедур')),
                ('expected_result', models.TextField(blank=True, verbose_name='Очікуваний результат')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substeps', to='core.auditstep', verbose_name='Крок')),
            ],
            options={
                'verbose_name': 'Підкрок аудиту (шаблон)',
                'verbose_name_plural': 'Підкроки аудиту (шаблони)',
                'ordering': ['step__order', 'order', 'id'],
                'unique_together': {('step', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StepAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, verbose_name='Ключ')),
                ('label', models.CharField(max_length=120, verbose_name='Текст кнопки')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Опис')),
                ('enabled', models.BooleanField(default=True, verbose_name='Увімкнено')),
                ('order', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Порядок')),
                ('scope', models.CharField(choices=[('step', 'На кроці'), ('substep', 'На підкроці')], default='step', max_length=20, verbose_name='Де доступна')),
                ('placement', models.CharField(choices=[('top', 'Вгорі'), ('inline', 'У блоці'), ('bottom', 'Внизу')], default='inline', max_length=20, verbose_name='Де показувати')),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Хто може бачити/виконувати цю дію.', related_name='aap_step_actions', to='auth.group', verbose_name='Дозволені групи')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.auditstep', verbose_name='Крок')),
                ('substep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.auditsubstep', verbose_name='Підкрок')),
            ],
            options={
                'verbose_name': 'Дія кроку (кнопка)',
                'verbose_name_plural': 'Дії кроків (кнопки)',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('step', 'key'), name='uniq_action_key_per_step'), models.UniqueConstraint(fields=('substep', 'key'), name='uniq_action_key_per_substep')],
            },
        ),
    ]
