# Generated by Django 5.2.8 on 2025-12-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auditstep_auditsubstep_stepaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Проєкт завершено'),
        ),
        migrations.CreateModel(
            name='AuditSubStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_substep_statuses', to='core.client')),
                ('substep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_statuses', to='core.auditsubstep')),
            ],
            options={
                'unique_together': {('client', 'substep')},
            },
        ),
    ]
