# Generated by Django 5.2.8 on 2025-12-24 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_client_is_completed_auditsubstepstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не виконано'), ('completed', 'Виконано')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substep_statuses', to='core.client')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_substeps', to=settings.AUTH_USER_MODEL)),
                ('substep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_statuses', to='core.auditsubstep')),
            ],
        ),
        migrations.DeleteModel(
            name='AuditSubStepStatus',
        ),
        migrations.AddIndex(
            model_name='clientsubstepstatus',
            index=models.Index(fields=['client', 'substep'], name='core_client_client__1fdc51_idx'),
        ),
        migrations.AddIndex(
            model_name='clientsubstepstatus',
            index=models.Index(fields=['client', 'status'], name='core_client_client__3e5e48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientsubstepstatus',
            unique_together={('client', 'substep')},
        ),
    ]
