"""
Django settings for aap_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
import dj_database_url

# ================== БАЗОВЫЕ НАСТРОЙКИ ==================

BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем переменные окружения из .env в корне проекта (актуально для локалки)
load_dotenv(BASE_DIR / ".env")

# ------------------ SECURITY / DEBUG -------------------

# В .env / на Render:
# DJANGO_SECRET_KEY=...
# DJANGO_DEBUG=False
# DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost,example.onrender.com

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-key")

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]

# ================== ПРИЛОЖЕНИЯ ==================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

# ================== MIDDLEWARE ==================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # для статики в проде
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aap_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # если будут кастомные шаблоны вне приложений – добавим сюда
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "aap_backend.wsgi.application"

# ================== БАЗА ДАННЫХ ==================

# В .env / на Render:
# DATABASE_URL=postgres://user:pass@host:5432/dbname?sslmode=require
# (на Neon лучше брать URL прямо из панели)

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv(
            "DATABASE_URL",
            # дефолт для локальной разработки, если .env не настроен
            "postgres://neondb_owner:npg_Z7naRgVTU2Ac@"
            "ep-square-rice-agowaoze-pooler.c-2.eu-central-1.aws.neon.tech:5432/"
            "neondb?sslmode=require&channel_binding=require",
        ),
        conn_max_age=600,
    )
}

# ================== ПАРОЛИ ==================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ================== ЛОКАЛИЗАЦИЯ ==================

LANGUAGE_CODE = "uk"

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True  # в новых версиях можно убрать, но не критично
USE_TZ = True

LANGUAGES = [
    ("uk", _("Ukrainian")),
    ("ru", _("Russian")),
    ("en", _("English")),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

# ================== СТАТИКА / МЕДИА ==================

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise: хранение и сжатие статики для продакшена
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = "login"

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/'   # можно и так, если хочешь