"""
Django settings for aap_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
import dj_database_url

# ================== БАЗОВЫЕ НАСТРОЙКИ ==================

BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем переменные окружения из .env в корне проекта (актуально для локалки)
load_dotenv(BASE_DIR / ".env")

# ------------------ SECURITY / DEBUG -------------------

# В .env / на Render:
# DJANGO_SECRET_KEY=...
# DJANGO_DEBUG=False
# DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost,example.onrender.com

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret-key")

DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]

# Флаг использования Cloudflare R2
USE_R2 = os.getenv("USE_R2", "false").lower() == "true"

# ================== ПРИЛОЖЕНИЯ ==================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

if USE_R2:
    INSTALLED_APPS.append("storages")

# ================== MIDDLEWARE ==================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # для статики в проде
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.CurrentOrganizationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aap_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # если будут кастомные шаблоны вне приложений – добавим сюда
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.aap_globals",
            ],
        },
    },
]

WSGI_APPLICATION = "aap_backend.wsgi.application"

# ================== БАЗА ДАННЫХ ==================

DATABASES = {
    "default": dj_database_url.parse(
        os.getenv(
            "DATABASE_URL",
            # дефолтный URL Neon, ОБЯЗАТЕЛЬНО с sslmode=require
            "postgres://neondb_owner:npg_Z7naRgVTU2Ac@"
            "ep-square-rice-agowaoze-pooler.c-2.eu-central-1.aws.neon.tech:5432/"
            "neondb?sslmode=require&channel_binding=require",
        ),
        # не держим соединения долго, чтобы Neon не успевал закрывать idle-подключения
        conn_max_age=0,
    )
}

# проверяем соединение перед использованием
DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

# ================== ПАРОЛИ ==================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ================== ЛОКАЛИЗАЦИЯ ==================

LANGUAGE_CODE = "uk"

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ("uk", _("Ukrainian")),
    ("ru", _("Russian")),
    ("en", _("English")),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

# ================== СТАТИКА / МЕДИА ==================

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

USE_R2 = os.getenv("USE_R2", "false").lower() == "true"

STORAGES = {
    "default": {
        "BACKEND": (
            "storages.backends.s3boto3.S3Boto3Storage"
            if USE_R2
            else "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if USE_R2:
    # читаем именно те переменные, которые у тебя в Render
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "auto")

    AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
# ================== АВТОРИЗАЦИЯ / РЕДИРЕКТЫ ==================

# имя URL'а для страницы логина
LOGIN_URL = "login"              # соответствует path("login/", ..., name="login")

# куда отправлять пользователя ПОСЛЕ успешного логина
LOGIN_REDIRECT_URL = "dashboard" # соответствует path("dashboard/", ..., name="dashboard")

# куда отправлять ПОСЛЕ выхода из системы
LOGOUT_REDIRECT_URL = "login"

# ===== CSRF / HTTPS FIX FOR RENDER =====

CSRF_TRUSTED_ORIGINS = [
    "https://aap-backend.onrender.com",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
